### ISSUE TITLE
missing older versions

### ISSUE THREAD

**Issue by pepsov** [axlecrusher/plex_download_urls#5]
I see that you are missing these older versions:
https://downloads.plex.tv/plex-media-server/1.13.5.5291-6fa5e50a8/plexmediaserver_1.13.5.5291-6fa5e50a8_amd64.deb
https://downloads.plex.tv/plex-media-server/1.13.4.5271-200287a06/plexmediaserver_1.13.4.5271-200287a06_amd64.deb

Below is also my list of even older PLEX versions. You might find that useful and include it in your list.
Not all of them work - the oldest seem to have been taken down, or were served from another site,  but I checked that the _amd64.deb versions at least as far back as  1.4.2.3400-ab906953b are still available on the PLEX official download site.

Keep up the good job - it's appreciated!

0.9.11.16.958-80f1748
0.9.12.0.1071-7b11cfc
0.9.12.11.1406-8403350
0.9.12.18.1520-6833552
0.9.12.19.1537-f38ac80
0.9.14.6.1620-e0b7243
0.9.15.1.1639-26325ea
0.9.15.2.1663-7efd046
0.9.15.3.1674-f46e7e6
0.9.15.4.1679-e4df231
0.9.15.5.1712-ba5070a
0.9.15.6.1714-7be11e1
0.9.16.0.1754-23623fb
0.9.16.2.1827-df572f6
0.9.16.3.1840-cece46d
0.9.16.4.1911-ee6e505
0.9.16.5.1966-81a3bf0
0.9.16.6.1993-5089475
0.9.17.2.2159-2bd156c
1.0.0.2261-a17e99e
1.0.1.2396-c094d0d
1.0.2.2413-7caf41d
1.0.3.2461-35f0caa
1.1.0.2611-ba905d2
1.1.3.2700-6f64a8d
1.1.4.2757-24ffd60
1.2.2.2857-d34b464
1.2.3.2914-1ff0f18
1.2.4.2949-4e494e4
1.2.6.2975-9394c87
1.2.7.2987-1bef33a
1.3.0.3059-6277334
1.3.1.3102-a8accf1
1.3.2.3112-1751929
1.3.3.3148-b38628e
1.3.4.3285-b46e0ea
1.4.2.3400-ab906953b
1.4.3.3433-03e4cfa35
1.4.4.3495-edef59192
1.5.0.3501-3b8374a5c
1.5.1.3520-ed60c70d6
1.5.2.3557-029f6ffbf
1.5.3.3580-4b377d295
1.5.4.3596-0d2d8c2be
1.5.5.3634-995f1dead
1.6.1.3722-4955e31cf
1.7.1.3856-757424396
1.9.2.4285-9f65b88ae
1.10.0.4523-648bc61d4
1.10.1.4561-9de2951fc
1.10.1.4602-f54242b6b
1.11.0.4633-70f9c31ed
1.11.0.4666-fc63598ba
1.11.1.4730-6967ec0b1
1.11.1.4753-da42c409e
1.11.1.4760-58bcb2957
1.11.1.4768-338ac2b75
1.11.2.4772-3e88ad3ba
1.11.3.4793-482972920
1.11.3.4803-c40bba82e
1.12.0.4829-6de959918
1.12.1.4871-6daee94e2
1.12.1.4885-1046ba85f
1.12.2.4929-29f6d1796
1.12.3.4947-b9dbb6d8e
1.12.3.4973-215c28d86
1.13.0.5003-8fcb5b6e5
1.13.0.5023-31d3c0c65
1.13.1.5063-b4605f76e
1.13.2.5102-4898d7d96
1.13.2.5142-3ba6662e9
1.13.3.5223-cd1e0da1b
1.13.4.5251-2e6e8f841
1.13.4.5271-200287a06
1.13.5.5291-6fa5e50a8
1.13.6.5339-115f087d6
1.13.8.5395-10d48da0d
1.13.9.5439-7303bc002
1.13.9.5456-ecd600442
1.14.0.5465-425e4ac90
1.14.0.5468-5a0183d2c
1.14.0.5470-9d51fdfaa
1.14.1.5487-dcc512d26
1.14.1.5488-cc260c476
1.15.0.659-9311f93fd
1.15.1.707-d893009fb
1.15.1.710-ece95b3a1
1.15.2.793-782228f99
1.15.3.835-5d4a5c895
1.15.3.876-ad6e39743
1.15.4.919-8e2884e4b
1.15.4.993-bb4a2cb6c
1.15.5.994-4610c6e8d
1.15.6.1079-78232c603
1.15.8.1163-005053bb5
1.15.8.1198-eadbcbb45
1.16.0.1220-147963d87
1.16.0.1226-7eb2c8f6f
1.16.1.1246-1d09ac057
1.16.1.1273-4b6101f87
1.16.1.1291-158e5b199
1.16.2.1297-4b7ace214
1.16.3.1402-22929c8a2
1.16.3.1433-359b06978
1.16.4.1469-6d5612c2f
1.16.5.1488-deeb86e7f
1.16.5.1554-1e5ff713d
1.16.6.1592-b9d49bdb7
1.17.0.1709-982421575
1.18.0.1846-f62172e99
1.18.1.1973-0f4abfbcc
1.18.2.2015-5a99a9a46
1.18.2.2029-36236cc4c
1.18.3.2111-5a96726d0
1.18.3.2129-41af4e729
1.18.3.2156-349e9837e
1.18.4.2164-2aa83397b
1.18.4.2171-ac2afe5f8
1.18.5.2260-056ab4be9
1.18.5.2309-f5213a238
1.18.7.2438-f342a5a43
1.18.7.2457-77cb9455c
1.18.8.2461-03ad9abb4
1.18.8.2468-5d395aa9d
1.18.8.2527-740d4c206
1.18.9.2571-e106a8a91
1.18.9.2578-513b381af
1.19.1.2589-2de7f3266
1.19.1.2621-b249be3b0
1.19.1.2630-72c16a276
1.19.1.2645-ccb6eb67e
1.19.2.2673-776106bc6
1.19.2.2702-776106bc6
1.19.2.2711-bab6de29f
1.19.3.2740-add6f438d
1.19.5.3035-864bbcbb7
1.19.5.3112-b23ab3896
1.20.1.3252-a78fef9a9
1.20.3.3437-f1f08d65b
1.20.3.3483-211702a9f
1.20.5.3562-eb17106d0
1.20.5.3600-47c0d9038
1.21.1.3766-7e23ef53c
1.21.1.3830-6c22540d5
1.21.1.3842-b0c7a97d9
1.21.2.3943-a91458577
1.21.3.4021-5a0a3e4b2
1.21.4.4054-bab510e86
1.22.1.4200-c073686f2
1.22.1.4228-724c56e62

**Comment by gabemiller832** [comment]
Hello there!

First of all, thank you for the good work, it's very useful!

I recently got to a point where I cannot install new Plex versions on my NAS (Synology DS918+, on DSM 7.1.1-42962 Update 6 at the moment) because HW is not strong enough anymore - at least this seems to be the case. 
(I'm having transcoding issues, no matter how I try to troubleshoot them by adjusting settings.)

Problem first presented itself with version 1.32.5.7328-2632c9d3a.
I had to roll back but the latest version I could find here was _PlexMediaServer-1.32.0.6918-6f393eda1-x86_64_DSM7.spk_ which is working fine but several versions are missing here between the two.
They are:
1.32.4.7195-7c8f9d3b6
1.32.3.7192-7aa441827
1.32.3.7162-b0a36929b
1.32.2.7100-248a2daf0
1.32.1.6999-91e1e2e2c
1.32.0.6973-a787c5a8e
1.32.0.6950-8521b7d99

I'm looking for the latter to be able to roll back to the latest one possible.

**Comment by axlecrusher** [comment]
> Hello there!
> 
> First of all, thank you for the good work, it's very useful!
> 
> I recently got to a point where I cannot install new Plex versions on my NAS (Synology DS918+, on DSM 7.1.1-42962 Update 6 at the moment) because HW is not strong enough anymore - at least this seems to be the case. (I'm having transcoding issues, no matter how I try to troubleshoot them by adjusting settings.)
> 
> Problem first presented itself with version 1.32.5.7328-2632c9d3a. I had to roll back but the latest version I could find here was _PlexMediaServer-1.32.0.6918-6f393eda1-x86_64_DSM7.spk_ which is working fine but several versions are missing here between the two. They are: 1.32.4.7195-7c8f9d3b6 1.32.3.7192-7aa441827 1.32.3.7162-b0a36929b 1.32.2.7100-248a2daf0 1.32.1.6999-91e1e2e2c 1.32.0.6973-a787c5a8e 1.32.0.6950-8521b7d99
> 
> I'm looking for the latter to be able to roll back to the latest one possible.

These missing versions should be included now.

**Comment by gabemiller832** [comment]
Thank you, big time!
